# MPLAB IDE generated this makefile for use with GNU make.
# Project: spletlelo.mcp
# Date: Mon May 16 15:21:13 2016

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

spletlelo.cof : spletlelo.o
	$(LD) /p18F452 "spletlelo.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"spletlelo.cof" /M"spletlelo.map" /W

spletlelo.o : spletlelo.c ../../../../Program\ Files\ (x86)/Microchip/mplabc18/v3.47/h/delays.h spletlelo.c ../../../../Program\ Files\ (x86)/Microchip/mplabc18/v3.47/h/p18f452.h ../../../../Program\ Files\ (x86)/Microchip/mplabc18/v3.47/h/p18cxxx.h
	$(CC) -p=18F452 "spletlelo.c" -fo="spletlelo.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "spletlelo.o" "spletlelo.cof" "spletlelo.hex"

